### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by georgiazhang** [jiangqy/DDSH-TIP2018#1]
Hello all, I noticed you indicated that the code would be announced soon,  I wonder if you can send me your codes or executive files which would give me a great of help in comprehending your algorithm and making some comparisons with mine. I will be appreciated for your reply as soon as possible, thanks for any help in advance, and for your fantastic work in the image retrieval area!!

**Comment by jiangqy** [comment]
Sorry about that. The code is not publically available because the paper is still under review by some conference. If you have any question for re-implementation, you can email me. (jiangqy@lamda.nju.edu.cn or qyjiang24@gmail.com)

**Comment by jiangqy** [comment]
Hi, @georgiazhang ,

I have released the code.
